export const services = [
  { id: 'applications', title: 'Enterprise applications', short: 'Business applications', tagline: 'Software that works the way you do.', body: 'Replace disconnected spreadsheets and manual handoffs with an application designed around your operations.', deliverables: ['Workflow mapping and product design', 'Role-based workspaces, approvals, and reporting', 'Application development, testing, and handover'], inputs: 'Your current process, user roles, business rules, and the systems the application needs to connect to.', fit: 'Internal operations, multi-step approvals, resource planning, and business-specific tools.', outcome: 'A shared workspace. A clearer way to work.' },
  { id: 'portals', title: 'Customer & partner portals', short: 'Customer / partner portals', tagline: 'A better front door to your business.', body: 'Give customers and partners a considered digital experience, connected to the work happening behind the scenes.', deliverables: ['Customer journeys and responsive interface design', 'Accounts, orders, documents, and service requests', 'Connections to your internal systems and notifications'], inputs: 'Your users, account model, service journey, and access to relevant back-office systems.', fit: 'Self-service customer experiences, partner collaboration, and account-based platforms.', outcome: 'Every relationship, connected to the right information.' },
  { id: 'automation', title: 'AI & workflow automation', short: 'AI & automation', tagline: 'Make room for the work that needs you.', body: 'Build focused automation around real tasks, with human review and practical evaluation designed into the workflow.', deliverables: ['Task discovery and feasibility assessment', 'Knowledge assistants, document processing, and workflows', 'Evaluation criteria, review steps, and operating guidance'], inputs: 'Representative tasks, suitable data, access permissions, and clear criteria for acceptable output.', fit: 'Repetitive document work, internal knowledge search, and assisted decision workflows.', outcome: 'Useful automation. People stay in control.' },
  { id: 'integrations', title: 'Integrations & data platforms', short: 'Integrations & data', tagline: 'Bring your business systems together.', body: 'Connect applications and data sources so the right information can move between teams and tools.', deliverables: ['Integration and data-flow architecture', 'APIs, CRM/ERP connections, and data pipelines', 'Dashboards, synchronization, and exception handling'], inputs: 'System documentation, API access, data ownership, and the rules for how records should move.', fit: 'Fragmented systems, duplicated data entry, and reporting spread across multiple tools.', outcome: 'Connected systems. More useful information.' },
  { id: 'modernization', title: 'Application modernization', short: 'Modernization', tagline: 'Move forward without losing what works.', body: 'Give an existing application a practical path to better usability, maintainability, and performance.', deliverables: ['Codebase, architecture, and user-experience assessment', 'Phased migration or redevelopment plan', 'Incremental releases, validation, and transition support'], inputs: 'The existing application, code and infrastructure access, known constraints, and business-critical workflows.', fit: 'Legacy applications, difficult maintenance, outdated experiences, and evolving requirements.', outcome: 'A considered transition to what comes next.' },
  { id: 'cloud', title: 'Cloud delivery & support', short: 'Cloud & support', tagline: 'Built to live beyond launch day.', body: 'Plan deployment, documentation, and ownership alongside development, with ongoing support agreed around your needs.', deliverables: ['Cloud setup and automated delivery pipelines', 'Monitoring, operating documentation, and handover', 'Maintenance and product improvement by agreement'], inputs: 'Your hosting requirements, operating responsibilities, release process, and support expectations.', fit: 'New product launches, deployment improvements, and maintaining business applications.', outcome: 'A clear launch. A practical plan for the life of the software.' },
];

export const journeys = [
  { label: 'Operations', title: 'Your operations, orchestrated.', source: ['Requests', 'Approvals', 'Assignments'], platform: 'Operations workspace', capabilities: 'Workflows · Roles · Reporting', result: ['Your people', 'One shared process'], description: 'Connect the work, from the first request to the final approval.', service: 'applications' },
  { label: 'Customers', title: 'Every interaction, connected.', source: ['Accounts', 'Orders', 'Service'], platform: 'Customer & partner portal', capabilities: 'Self-service · APIs · Notifications', result: ['Your customers', 'Your internal systems'], description: 'Bring a considered customer experience and your business systems together.', service: 'portals' },
  { label: 'Data', title: 'Information with a purpose.', source: ['Applications', 'Documents', 'Data sources'], platform: 'Connected data platform', capabilities: 'Integrations · Search · Intelligence', result: ['Your teams', 'Useful information'], description: 'Put relevant business information where your teams can use it.', service: 'integrations' },
];

export const solutions = [
  { label: 'Run operations', number: '01', title: 'From a request to a clear next step.', body: 'An operations workspace connecting requests, approvals, assignments, and reporting around your own business rules.', users: 'Operations managers and delivery teams', nodes: ['Request', 'Review', 'Assign', 'Track'], details: ['Role-based work queues', 'Approval rules and notifications', 'A shared view of progress'], boundary: 'Connect to the tools holding your customer, finance, or resource data.', service: 'applications' },
  { label: 'Serve customers', number: '02', title: 'A single place to work with your business.', body: 'A self-service portal for account information, orders, documents, and service requests, connected to internal operations.', users: 'Customers, partners, and account teams', nodes: ['Sign in', 'Find', 'Request', 'Follow up'], details: ['Account-specific information', 'Documents and service workflows', 'Updates from back-office systems'], boundary: 'Integrate with your CRM, order management, or service platform.', service: 'portals' },
  { label: 'Connect knowledge', number: '03', title: 'Put your business knowledge to work.', body: 'A searchable knowledge platform that brings relevant documents and business information into one useful experience.', users: 'Knowledge workers and business teams', nodes: ['Connect', 'Organize', 'Search', 'Review'], details: ['Permission-aware retrieval', 'Sources alongside answers', 'Human review and evaluation'], boundary: 'Start with agreed data sources, access rules, and a clearly defined task.', service: 'automation' },
];

export const process = [
  { name: 'Discover', heading: 'Start with the right problem.', body: 'Understand your users, workflows, systems, and constraints before defining what to build.', output: 'A scoped brief, priorities, assumptions, and success criteria.', review: 'Align on the problem, scope boundaries, and the people involved.', points: ['Business and user context', 'Existing systems and dependencies', 'Priorities and scope'] },
  { name: 'Design', heading: 'Make the solution tangible.', body: 'Translate the brief into journeys, interfaces, architecture, and a phased plan that your team can review.', output: 'User journeys, interface designs, architecture, and a delivery plan.', review: 'Review the proposed experience and technical approach before development.', points: ['User journeys and interface design', 'System architecture', 'Phased delivery plan'] },
  { name: 'Develop', heading: 'Progress you can review.', body: 'Build in manageable increments, test the important workflows, and incorporate feedback at agreed review points.', output: 'Reviewable releases, tests, and delivery documentation.', review: 'Review working increments and agree priorities for the next release.', points: ['Incremental development', 'Testing and integration', 'Feedback and refinement'] },
  { name: 'Evolve', heading: 'A considered path beyond launch.', body: 'Prepare the release, document the system, and agree who operates, maintains, and improves it.', output: 'Deployment, handover, and an agreed operating or support plan.', review: 'Confirm acceptance, ownership, and the next steps for the application.', points: ['Deployment and validation', 'Documentation and handover', 'Support by agreement'] },
];

export const technologies = [
  { label: 'Applications', body: 'Choose a stack that fits the product, your team, and the expected life of the application.', tools: ['React / Next.js', 'TypeScript', 'Node.js', 'Java / Spring Boot'] },
  { label: 'Data & integration', body: 'Build around the data you own and the systems you already use, with explicit integration boundaries.', tools: ['PostgreSQL', 'Python', 'APIs & integrations', 'Data pipelines'] },
  { label: 'Applied AI', body: 'Start with a useful task, suitable data, and evaluation criteria. Keep review and operating cost in view.', tools: ['Knowledge retrieval', 'Document workflows', 'Model integrations', 'Evaluation'] },
  { label: 'Delivery', body: 'Consider operating cost, deployment, observability, and maintainability from the start.', tools: ['Cloud infrastructure', 'CI/CD', 'Automated testing', 'Observability'] },
];

export const team = [
  { name: 'Anurag Mishra', role: 'CEO', focus: 'Product & software direction', photo: '/team/anurag', bio: 'Connects business requirements with application design, full-stack development, and practical AI capabilities.' },
  { name: 'Abhinav Das', role: 'Managing Director', focus: 'Business & client relationships', photo: '/team/abhinav', bio: 'Leads business relationships and engagement coordination, keeping priorities and communication clear throughout a project.' },
  { name: 'Himanshu Pandey', role: 'CTO', focus: 'Architecture & engineering', photo: '/team/himanshu', bio: 'Guides architecture and engineering across applications, APIs, data, and cloud infrastructure, with maintainability at the center.' },
];

export const faqs = [
  { q: 'What kind of software can you build?', a: 'Business applications, customer and partner portals, workflow automation, integrations, data platforms, and modernization. We start with the business problem and define the right scope together.' },
  { q: 'Can you work with our existing systems?', a: 'Yes. Discovery establishes integration options, access requirements, data ownership, dependencies, and migration constraints so the application fits into your existing environment.' },
  { q: 'How do you define scope, cost, and timeline?', a: 'We start with your goals, workflows, and constraints, then propose scope, milestones, and a commercial model. Estimates depend on complexity, integrations, and the level of definition. Assumptions are made explicit before work begins.' },
  { q: 'Who owns the software and source code?', a: 'Ownership, repository access, documentation, and handover are agreed in the project contract. The delivery approach is designed to give your team a maintainable system and a clear path to operate it.' },
  { q: 'What happens after launch?', a: 'Deployment, documentation, and handover are planned as part of delivery. Ongoing maintenance, monitoring, and new features can be covered through a separate support arrangement.' },
  { q: 'How will we work together?', a: 'We work remotely with agreed review points, communication channels, and a shared delivery plan. Your team stays involved in priorities, feedback, and acceptance throughout the project.' },
];
